web/app/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
]


web/blog/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import IndexView, BlogDetailView, CommentAddView, BlogAPIView, CommentAPIAddView

app_name = 'blog'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('<str:slug>/', BlogDetailView.as_view(), name='detail'),
    path('api/blog/', BlogAPIView.as_view(), name='blog_api'),
    # path('api/comment/', CommentAddView.as_view(), name='comment_api'),
    path('<str:slug>/add-comment/', login_required(CommentAPIAddView.as_view({'post': 'create', 'get': 'get'})),
         name='add_comment'),
]

web/src/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from rest_framework_jwt.views import verify_jwt_token, refresh_jwt_token
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('', include('app.urls')),
    path('blog/', include('blog.urls')),
    path('user/', include('authentificate.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('profileuser.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('token/verify/', verify_jwt_token, name="verify_auth_token"),
    path('token/refresh/', refresh_jwt_token, name="refresh_auth_token"),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    # path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

# handler404 = 'app.views.custom_handler404'
# handler500 = 'app.views.custom_handler500'


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web/templates/layer.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" type="image/png" href="{% static 'app/favicon.ico' %}"/>
    <title>{% block title %} Blog {% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css"/>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'app/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'app/css/blog-home.css' %}" rel="stylesheet">
    <link href="{% static 'app/css/site.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/fe539a9d82.js" crossorigin="anonymous"></script>
    {% block head %} {% endblock %}
</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'main:index' %}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ">
<!--                <li class="nav-item active">-->
<!--                    <a class="nav-link" href="{% url 'main:index' %}"><i class="fa fa-home"></i> Home-->
<!--                        <span class="sr-only">(current)</span>-->
<!--                    </a>-->
<!--                </li>-->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:index' %}"><i class="fas fa-book"></i>Blog</a>
                </li>
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="#">About</a>-->
<!--                </li>-->
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="#">Services</a>-->
<!--                </li>-->
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="#">Contact</a>-->
<!--                </li>-->
            </ul>
            <ul class="nav navbar-nav ml-auto">
                {% include 'loginpartial.html' %}
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
<div class="container wrapper content">
    {% block row %}
    <div class="row">
        {% endblock row %}
        {% block content %}{% endblock %}

        {% block sidebar %}
        <!-- Sidebar Widgets Column -->
        {% endblock %}
        {% block row_end %}
    </div>
    <!-- /.row -->
    {% endblock row_end %}

</div>
<!-- /.container -->

<!-- Footer -->
<footer class="py-5 bg-dark footer">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; WebSite {{site}}  {% now "Y" %}</p>
    </div>
    <!-- /.container -->
</footer>

<!-- Bootstrap core JavaScript -->
<script src="{% static 'app/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'app/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
{% block scripts %}{% endblock %}
<script>
      $(document).ready(function(){
          {% block jquery %} {% endblock %}
      })

</script>
</body>

</html>

web/templates/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="{% url 'main:logout' %}" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">
            {% if user.is_staff %}
            <a target="_blank" style="text-decoration: none" href="{% url 'admin:index' %}"> Hello, {{ user.get_full_name }}!</a>

            {% else %}
                Hello, {{ user.get_full_name }}!
            {% endif %}
        </span></li>
        <li><span class="navbar-brand">
            <a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></span></li>
    </ul>
</form>

{% else %}

<li><span class="navbar-brand"><a href="{% url 'account_login' %}">Sign in</a></span></li>
<li><span class="navbar-brand"><a href="{% url 'account_signup' %}">Sign up</a></span></li>

{% endif %}