web/app/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
]


web/blog/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import IndexView, BlogDetailView, CommentAddView, BlogAPIView, CommentAPIAddView

app_name = 'blog'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('<str:slug>/', BlogDetailView.as_view(), name='detail'),
    path('api/blog/', BlogAPIView.as_view(), name='blog_api'),
    # path('api/comment/', CommentAddView.as_view(), name='comment_api'),
    path('<str:slug>/add-comment/', login_required(CommentAPIAddView.as_view({'post': 'create', 'get': 'get'})),
         name='add_comment'),
]

web/src/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from rest_framework_jwt.views import verify_jwt_token, refresh_jwt_token
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('', include('app.urls')),
    path('blog/', include('blog.urls')),
    path('user/', include('authentificate.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('profileuser.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('token/verify/', verify_jwt_token, name="verify_auth_token"),
    path('token/refresh/', refresh_jwt_token, name="refresh_auth_token"),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    # path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

# handler404 = 'app.views.custom_handler404'
# handler500 = 'app.views.custom_handler500'


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web/blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.text import slugify
from rest_framework.reverse import reverse

from .managers import PublishedManager
User = get_user_model()


def poster_upload_to(instance, file):
    now = timezone.now()
    return f"blog_images/{instance.author}/{file}"


class Blog(models.Model):
    title = models.CharField(verbose_name='Title', max_length=200)
    slug = models.SlugField(verbose_name='Url', allow_unicode=True, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    content = models.TextField('Content')
    poster = models.ImageField('Poster', upload_to=poster_upload_to, default='blog_images/no_image.png')
    publish = models.DateTimeField('Publish date', auto_now_add=True)
    draft = models.BooleanField('Draft', default=True)

    objects = models.Manager()

    def __str__(self):
        return f"{self.title}: {self.author.email}"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True).lower()
        return super().save(*args, **kwargs)

    def get_comments(self):
        # print(dir(self))
        return self.blog_comment.filter(parent__isnull=True).order_by('-created_date')

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'slug': self.slug})

    def is_published(self):
        return not self.draft

    is_published.short_description = 'Published'
    is_published.boolean = True


class Comment(models.Model):
    # author = models.CharField('Author', max_length=200)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_set')
    comment = models.TextField('Comment')
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_comment')
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='parent_comment', null=True, blank=True)
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.author}: {self.comment[:10]}"

web/blog/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Comment


class CommentForm(forms.ModelForm):
    # author = forms.CharField(required=True, widget=forms.TextInput(attrs={
    #     'class': 'form-control',
    #     'placeholder': 'your name'
    # }))
    comment = forms.CharField(required=True, widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'your comment',
        'id': 'contact_comment'
    }))

    def clean_comment(self):
        comment = self.cleaned_data.get('comment')
        return comment

    def clean(self):
        data = self.cleaned_data
        author = data.get('author')
        comment = data.get('comment')
        if comment == 'valid':
            raise ValidationError('Wrong comment!')
        print(data)
        return data

    class Meta:
        model = Comment
        fields = ('author', 'comment')

web/blog/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from rest_framework import status
from rest_framework.generics import get_object_or_404
from django.shortcuts import redirect
from django.urls import reverse
from django.views import View
from django.views.generic import DetailView, ListView
from rest_framework.generics import GenericAPIView, CreateAPIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import APIView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CommentForm
from .serializers import *
from rest_framework.response import Response
from .models import Blog, Comment
from rest_framework.viewsets import GenericViewSet
from .services import BlogService

User = get_user_model()


class BlogAPIView(GenericAPIView):
    serializer_class = BlogSerializer

    def get_queryset(self):
        return BlogService.get_blogs()

    def get(self, request):
        serializer = self.get_serializer(self.get_queryset(), many=True)
        return Response(serializer.data)


class CommentAPIAddView(GenericViewSet):
    # serializer_class = CommentSerializer

    permission_classes = (IsAuthenticated,)

    def get_serializer_class(self):
        if self.action == 'get':
            return CommentSerializer_
        elif self.action == 'create':
            return CommentSerializer

        return CommentSerializer

    def get_queryset(self):
        return BlogService.get_comments()

    def get(self, request, slug=None):
        serializer = self.get_serializer(self.get_queryset(), many=True)
        return Response(serializer.data)

    def get_serializer_context(self):
        data = super(CommentAPIAddView, self).get_serializer_context()
        data['blog'] = self.get_blog_object()
        return data

    def get_blog_object(self):
        return BlogService.get_blog_by_slug(slug=self.kwargs.get('slug'))

    def create(self, request, slug, **kwargs):

        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        comment = serializer.save()

        return Response(serializer.cleaned_data(comment), status=status.HTTP_201_CREATED)


class IndexView(ListView):
    template_name = 'blog/post_list.html'
    queryset = Blog.objects.order_by('publish')
    context_object_name = 'blogs'


class BlogDetailView(DetailView):
    template_name = 'blog/post_detail.html'
    slug_field = 'slug'
    context_object_name = 'blog'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['comments'] = Comment.objects.filter(blog=self.get_object())
        if self.request.user.is_authenticated:
            data['form'] = CommentForm()
        return data

    def get_object(self, queryset=None):
        slug = self.kwargs.get('slug')
        return Blog.objects.get(slug=slug)

    def get_queryset(self):
        return Blog.objects.all()


class CommentAddView(APIView):

    def post(self, request, slug, *args, **kwargs):
        form = CommentForm(data=request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.blog = Blog.objects.get(slug=slug)
            user = request.POST.get('author')
            form.author_id = int(user)
            if request.POST.get('parent'):
                form.parent_id = int(request.POST.get('parent'))
                # form.parent = Comment.objects.get(id=int(request.POST.get('parent')))
            # print(request.POST)
            form.save()
        return redirect(reverse('blog:detail', kwargs={'slug': slug}))

web/blog/templates/blog/detail_old.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Blog Post - Start Bootstrap Template</title>

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="css/blog-post.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Start Bootstrap</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4">Post Title</h1>

        <!-- Author -->
        <p class="lead">
          by
          <a href="#">Start Bootstrap</a>
        </p>

        <hr>

        <!-- Date/Time -->
        <p>Posted on January 1, 2019 at 12:00 PM</p>

        <hr>

        <!-- Preview Image -->
        <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">

        <hr>

        <!-- Post Content -->
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>

        <blockquote class="blockquote">
          <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
          <footer class="blockquote-footer">Someone famous in
            <cite title="Source Title">Source Title</cite>
          </footer>
        </blockquote>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>

        <hr>

        <!-- Comments Form -->
        <div class="card my-4">
          <h5 class="card-header">Leave a Comment:</h5>
          <div class="card-body">
            <form>
              <div class="form-group">
                <textarea class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
          </div>
        </div>

        <!-- Single Comment -->
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
          </div>
        </div>

        <!-- Comment with nested comments -->
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.

            <div class="media mt-4">
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">Commenter Name</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
              </div>
            </div>

            <div class="media mt-4">
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">Commenter Name</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
              </div>
            </div>

          </div>
        </div>

      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Search</h5>
          <div class="card-body">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-append">
                <button class="btn btn-secondary" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>

        <!-- Categories Widget -->
        <div class="card my-4">
          <h5 class="card-header">Categories</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">Web Design</a>
                  </li>
                  <li>
                    <a href="#">HTML</a>
                  </li>
                  <li>
                    <a href="#">Freebies</a>
                  </li>
                </ul>
              </div>
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">JavaScript</a>
                  </li>
                  <li>
                    <a href="#">CSS</a>
                  </li>
                  <li>
                    <a href="#">Tutorials</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <!-- Side Widget -->
        <div class="card my-4">
          <h5 class="card-header">Side Widget</h5>
          <div class="card-body">
            You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
          </div>
        </div>

      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>

web/blog/templates/blog/index.html
{% extends 'layer.html' %}

{% block sidebar %}
<!-- Sidebar Widgets Column -->
<!--<div class="col-md-4">-->

    <!-- Search Widget -->
<!--    <div class="card my-4">-->
<!--        <h5 class="card-header">Search</h5>-->
<!--        <div class="card-body">-->
<!--            <div class="input-group">-->
<!--                <input type="text" class="form-control" placeholder="Search for...">-->
<!--                <span class="input-group-append">-->
<!--                <button class="btn btn-secondary" type="button">Go!</button>-->
<!--              </span>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->

    <!-- Categories Widget -->
<!--    <div class="card my-4">-->
<!--        <h5 class="card-header">Categories</h5>-->
<!--        <div class="card-body">-->
<!--            <div class="row">-->
<!--                <div class="col-lg-6">-->
<!--                    <ul class="list-unstyled mb-0">-->
<!--                        <li>-->
<!--                            <a href="#">Web Design</a>-->
<!--                        </li>-->
<!--                        <li>-->
<!--                            <a href="#">HTML</a>-->
<!--                        </li>-->
<!--                        <li>-->
<!--                            <a href="#">Freebies</a>-->
<!--                        </li>-->
<!--                    </ul>-->
<!--                </div>-->
<!--                <div class="col-lg-6">-->
<!--                    <ul class="list-unstyled mb-0">-->
<!--                        <li>-->
<!--                            <a href="#">JavaScript</a>-->
<!--                        </li>-->
<!--                        <li>-->
<!--                            <a href="#">CSS</a>-->
<!--                        </li>-->
<!--                        <li>-->
<!--                            <a href="#">Tutorials</a>-->
<!--                        </li>-->
<!--                    </ul>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->

    <!-- Side Widget -->
<!--    <div class="card my-4">-->
<!--        <h5 class="card-header">Side Widget</h5>-->
<!--        <div class="card-body">-->
<!--            You can put anything you want inside of these side widgets. They are easy to use, and feature the new-->
<!--            Bootstrap 4 card containers!-->
<!--        </div>-->
<!--    </div>-->

<!--</div>-->
{% endblock %}

web/blog/templates/blog/post_detail.html
{% extends 'blog/index.html' %}
{% load static %}

{% block content %}
<!-- Post Content Column -->
<div class="col-lg-8">

    <!-- Title -->
    <h1 class="mt-4">Post Title</h1>

    <!-- Author -->
    <p class="lead">
        <a href="#">{{ blog.author }}</a>
    </p>

    <hr>

    <!-- Date/Time -->
    <p>{{ blog.publish | date:"d M Y" }}</p>

    <hr>

    <!-- Preview Image -->
    <img class="img-fluid rounded" width="300" height="500" src="{{ blog.poster.url }}" alt="">

    <hr>

    <!-- Post Content -->
    <p class="lead">{{ blog.content | safe }}</p>

    <hr>
    {% if user.is_authenticated %}
    <!-- Comments Form -->
    <div class="card my-4">
        <h5 class="card-header">Leave a Comment:</h5>
        <div class="card-body">
            <form method="POST" action="{% url 'blog:add_comment' blog.slug %}" id="add_comment">
                {% csrf_token %}
                <div class="form-group">
                    <input type="hidden" name="author" value="{{ user.id }}">
                    <input type="hidden" name="parent" id="contact_parent" value="">
                    <p>{{ form.comment }}</p>
                    <p>{{ form.comment.errors }}</p>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>

    {% endif %}

    <!-- Single Comment -->
    {% for comment in blog.get_comments %}
    <div class="media mb-4">
        <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
        <div class="media-body">
            <h5 class="mt-0">{{ comment.author }}</h5>
            {{ comment.comment }}
            <br>
            <!--            <input type="button" class="btn btn-primary" value="answer">-->
            <!--            <button type="submit" class="btn btn-primary">answer</button>-->
            <a href="#add_comment" onclick="add_parent('{{ comment.id }}', '{{ comment.author }}')">answer</a>
            {% for parent_comment in comment.parent_comment.all %}
            <div class="media mt-4">
                <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                <div class="media-body">
                    <h5 class="mt-0">{{ parent_comment.author }}</h5>
                    {{ parent_comment.comment }}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endfor %}

</div>

{% endblock %}
{% block scripts %}
<script src="{% static 'blog/js/add_parent_comment.js' %}"></script>
{% endblock %}

web/blog/templates/blog/post_list.html
{% extends 'blog/index.html' %}
{% load static %}


{% block content %}
<div class="col-md-8">
    <h1 class="my-4">Blogs
<!--        <small>Secondary Text</small>-->
    </h1>
    <!-- Blog Post -->
    {% for blog in blogs %}
    <div class="card mb-4">
        <img class="card-img-top" width="200" height="500" src="{{ blog.poster.url }}" alt="Card image cap">
        <div class="card-body">
            <h2 class="card-title">{{ blog.title }}</h2>
            <p class="card-text">{{ blog.content | truncatewords:60 | safe }}</p>
            <a href="{{ blog.get_absolute_url }}" class="btn btn-primary">Read More</a>
        </div>
        <div class="card-footer text-muted">
            {{ blog.publish | date:"d M Y" }}
            <a href="#">{{ blog.author }}</a>
        </div>
    </div>
    {% endfor %}

    <!-- Pagination -->
    <ul class="pagination justify-content-center mb-4">
        <li class="page-item">
            <a class="page-link" href="#">&larr; Older</a>
        </li>
        <li class="page-item disabled">
            <a class="page-link" href="#">Newer &rarr;</a>
        </li>
    </ul>


    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                {% for post in posts %}
                <p>{{ post.id}} - {{ post.title }} - {{ post.slug }} - {{ post.publish}} - Draft: {{ post.draft }}</p>

                <a href="{{ post.get_absolute_url }}">{{ post.title}}</a>
                <p> {{ post.content | safe | truncatewords:100}}</p>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}